# create virtual environment
env:
    uv venv .venv

# install project dependencies
install:
    uv sync --extra test

# build docker image
build:
    docker build -t kv-store-service:latest -f Dockerfile .

# run unit tests
test:
    uv run pytest -q tests/

# run service code locally
start PORT='8000':
    #!/usr/bin/env bash
    export PORT={{PORT}}
    uv run python -m src.main
